---
title: "Flexdashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(collapse = TRUE, message = FALSE)
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

```{r}
data('rest_inspec')
# Use part of the dataset
rest_df = 
  rest_inspec %>%
  janitor::clean_names() %>%
  filter(
    substr(inspection_date, 1, 4) == 2017,
    boro != 'Missing') %>%
  drop_na(score)
```

```{r}
scatter_plot = 
  rest_df %>%
  group_by(boro, inspection_date) %>%
  mutate(mean_score = mean(score)) %>%
  select(boro, inspection_date, mean_score) %>%
  plot_ly(x = ~inspection_date, y = ~mean_score, color = ~boro, type = 'scatter', colors = 'viridis') %>%
  layout(
    xaxis = list(title = "Inspection Date"),
    yaxis = list(title = "Mean Score")
  )
```

```{r}
box_plot = 
  rest_df %>%
  plot_ly(y = ~score, color = ~boro, type = 'box', colors = 'viridis') %>%
  layout(
    xaxis = list(title = "Region"),
    yaxis = list(title = "Score")
    )
```

```{r}
Score_cui = 
  rest_df %>%
  group_by(cuisine_description) %>%
  summarize(mean_score = mean(score)) %>%
  arrange(-mean_score, cuisine_description) %>%
  head(10)

bar_plot = 
  Score_cui %>%
  mutate(cuisine_description = fct_reorder(cuisine_description, -mean_score)) %>%
  plot_ly(x = ~reorder(cuisine_description, -mean_score), y = ~mean_score, color = ~cuisine_description, type = 'bar', colors = 'viridis') %>%
  layout(
    xaxis = list(title = "Cuisine Description"),
    yaxis = list(title = "Mean Score")
    )
```


Column {data-width=650}
-----------------------------------------------------------------------
### Score distribution of NYC restaurants in differernt selected regions in 2017
```{r}
box_plot
```

Column{data-width = 350}
-----------------------------------------------------------------------
### Mean score distribution of restaurants in selected regions at different time in 2017
```{r}
scatter_plot
```

### Top 10 restaurants with highest mean inspection scores (lowest grade and worst performance) in 2017

```{r}
bar_plot
```

